// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/zhuoqingbin/pbs/evsepb/evsepb.proto

package evsepb

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EvseCtrlReq) Validate() error {
	return nil
}
func (this *EvseCtrlReply) Validate() error {
	return nil
}
func (this *EvseStreamReq) Validate() error {
	if this.Apdu != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Apdu); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Apdu", err)
		}
	}
	return nil
}
func (this *EvseStreamReply) Validate() error {
	for _, item := range this.Apdus {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Apdus", err)
			}
		}
	}
	return nil
}
func (this *GetConnectorByIDReq) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	return nil
}
func (this *GetConnectorByIDReply) Validate() error {
	if this.Evse != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Evse); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Evse", err)
		}
	}
	if this.Connector != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Connector); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Connector", err)
		}
	}
	return nil
}
func (this *GetConnectorByNOReq) Validate() error {
	if !(this.Cno > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Cno", fmt.Errorf(`value '%v' must be greater than '0'`, this.Cno))
	}
	return nil
}
func (this *GetConnectorByNOReply) Validate() error {
	if this.Evse != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Evse); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Evse", err)
		}
	}
	if this.Connector != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Connector); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Connector", err)
		}
	}
	return nil
}
func (this *GetEvseByIDReq) Validate() error {
	if !(this.Id > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Id", fmt.Errorf(`value '%v' must be greater than '0'`, this.Id))
	}
	return nil
}
func (this *GetEvseByIDReply) Validate() error {
	if this.Evse != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Evse); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Evse", err)
		}
	}
	for _, item := range this.Connectors {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Connectors", err)
			}
		}
	}
	return nil
}
func (this *GetEvseBySNReq) Validate() error {
	if this.Sn == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Sn", fmt.Errorf(`value '%v' must not be an empty string`, this.Sn))
	}
	return nil
}
func (this *GetEvseBySNReply) Validate() error {
	if this.Evse != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Evse); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Evse", err)
		}
	}
	for _, item := range this.Connectors {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Connectors", err)
			}
		}
	}
	return nil
}
func (this *UpsertEvseReply) Validate() error {
	if this.Evse != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Evse); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Evse", err)
		}
	}
	return nil
}
func (this *Evse) Validate() error {
	if this.Sn == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("Sn", fmt.Errorf(`value '%v' must not be an empty string`, this.Sn))
	}
	if this.EvseModel != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EvseModel); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EvseModel", err)
		}
	}
	return nil
}
func (this *Connector) Validate() error {
	return nil
}
